version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    target-branch: "main"
    rebase-strategy: "auto"
    assignees:
      - "ayayousef2000"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions-all:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    target-branch: "main"
    rebase-strategy: "auto"
    assignees:
      - "ayayousef2000"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    groups:
      commitlint:
        patterns:
          - "@commitlint/*"
      npm-all:
        patterns:
          - "*"
        exclude-patterns:
          - "@commitlint/*"
    open-pull-requests-limit: 5